export const barsData = {
  labels: [
    "2000/01",
    "2001/02",
    "2002/03",
    "2003/04",
    "2004/05",
    "2005/06",
    "2006/07",
    "2007/08",
    "2008/09",
    "2009/10",
    "2010/11",
    "2011/12",
    "2012/13",
    "2013/14",
    "2014/15",
    "2015/16",
    "2016/17",
    "2017/18",
    "2018/19",
  ],
  data: [
    "1237",
    "1200",
    "1195",
    "810",
    "1773",
    "2016",
    "1783",
    "1462",
    "1944",
    "2788",
    "2198",
    "707",
    "588",
    "3008",
    "2542",
    "2091",
    "1342",
    "2499",
    "4094",
  ],
  lineData: [
    "0.70",
    "0.80",
    "0.60",
    "0.75",
    "0.85",
    "0.65",
    "0.90",
    "0.80",
    "1.20",
    "1.50",
    "1.30",
    "1.55",
    "1.55",
    "1.67",
    "1.80",
    "1.85",
    "2.35",
    "2.20",
    "1.95",
  ],
};
export const steps = [
  {
    id: "1",
    message: "What is your name?",
    trigger: "2",
  },
  {
    id: "2",
    user: true,
    trigger: "3",
  },
  {
    id: "3",
    message: "Hi {previousValue}, nice to meet you!. Bye",
    end: true,
  },
];
export const tableData = [
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Afghanistan",
    Value: "124",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Afghanistan",
    Value: "22",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Afghanistan",
    Value: "80",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Afghanistan",
    Value: "20",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Afghanistan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Afghanistan",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Afghanistan",
    Value: "75",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Afghanistan",
    Value: "4",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Afghanistan",
    Value: "74",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Afghanistan",
    Value: "100",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Afghanistan",
    Value: "100",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Afghanistan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Afghanistan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Afghanistan",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Afghanistan",
    Value: "0.6",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Albania",
    Value: "1",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Albania",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Albania",
    Value: "2",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Albania",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Albania",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Albania",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Albania",
    Value: "2",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Albania",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Albania",
    Value: "2",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Albania",
    Value: "2",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Albania",
    Value: "2",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Albania",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Albania",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Albania",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Albania",
    Value: "2",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Algeria",
    Value: "216",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Algeria",
    Value: "122",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Algeria",
    Value: "550",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Algeria",
    Value: "43",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Algeria",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Algeria",
    Value: "425",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Algeria",
    Value: "125",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Algeria",
    Value: "308",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Algeria",
    Value: "163",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Algeria",
    Value: "593",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Algeria",
    Value: "593",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Algeria",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Algeria",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Algeria",
    Value: "334",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Algeria",
    Value: "0.75",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Argentina",
    Value: "248",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Argentina",
    Value: "396",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Argentina",
    Value: "475",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Argentina",
    Value: "432",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Argentina",
    Value: "211",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Argentina",
    Value: "50",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Argentina",
    Value: "425",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Argentina",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Argentina",
    Value: "722",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Argentina",
    Value: "1118",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Argentina",
    Value: "1118",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Argentina",
    Value: "202",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Argentina",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Argentina",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Argentina",
    Value: "2.91",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Armenia",
    Value: "65",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Armenia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Armenia",
    Value: "65",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Armenia",
    Value: "3",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Armenia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Armenia",
    Value: "60",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Armenia",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Armenia",
    Value: "8",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Armenia",
    Value: "60",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Armenia",
    Value: "68",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Armenia",
    Value: "68",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Armenia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Armenia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Armenia",
    Value: "8",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Armenia",
    Value: "0.92",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Australia",
    Value: "3454",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Australia",
    Value: "387",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Australia",
    Value: "2200",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Australia",
    Value: "963",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Australia",
    Value: "3967",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Australia",
    Value: "1300",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Australia",
    Value: "900",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Australia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Australia",
    Value: "6743",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Australia",
    Value: "7130",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Australia",
    Value: "7130",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Australia",
    Value: "3924",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Australia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Australia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Australia",
    Value: "1.95",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Azerbaijan",
    Value: "109",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Azerbaijan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Azerbaijan",
    Value: "150",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Azerbaijan",
    Value: "4",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Azerbaijan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Azerbaijan",
    Value: "125",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Azerbaijan",
    Value: "25",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Azerbaijan",
    Value: "4",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Azerbaijan",
    Value: "150",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Azerbaijan",
    Value: "154",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Azerbaijan",
    Value: "154",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Azerbaijan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Azerbaijan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Azerbaijan",
    Value: "4",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Azerbaijan",
    Value: "1.38",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Bangladesh",
    Value: "7",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Bangladesh",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Bangladesh",
    Value: "7",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Bangladesh",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Bangladesh",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Bangladesh",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Bangladesh",
    Value: "7",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Bangladesh",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Bangladesh",
    Value: "7",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Bangladesh",
    Value: "7",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Bangladesh",
    Value: "7",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Bangladesh",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Bangladesh",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Bangladesh",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Bangladesh",
    Value: "1",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Belarus",
    Value: "736",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Belarus",
    Value: "88",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Belarus",
    Value: "1450",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Belarus",
    Value: "56",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Belarus",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Belarus",
    Value: "1000",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Belarus",
    Value: "450",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Belarus",
    Value: "40",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Belarus",
    Value: "1378",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Belarus",
    Value: "1506",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Belarus",
    Value: "1506",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Belarus",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Belarus",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Belarus",
    Value: "67",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Belarus",
    Value: "1.87",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Bhutan",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Bhutan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Bhutan",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Bhutan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Bhutan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Bhutan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Bhutan",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Bhutan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Bhutan",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Bhutan",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Bhutan",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Bhutan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Bhutan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Bhutan",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Bhutan",
    Value: "1",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Bolivia",
    Value: "57",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Bolivia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Bolivia",
    Value: "44",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Bolivia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Bolivia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Bolivia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Bolivia",
    Value: "44",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Bolivia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Bolivia",
    Value: "44",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Bolivia",
    Value: "44",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Bolivia",
    Value: "44",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Bolivia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Bolivia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Bolivia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Bolivia",
    Value: "0.77",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Bosnia and Herzegovina",
    Value: "23",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Bosnia and Herzegovina",
    Value: "4",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Bosnia and Herzegovina",
    Value: "60",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Bosnia and Herzegovina",
    Value: "3",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Bosnia and Herzegovina",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Bosnia and Herzegovina",
    Value: "50",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Bosnia and Herzegovina",
    Value: "10",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Bosnia and Herzegovina",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Bosnia and Herzegovina",
    Value: "54",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Bosnia and Herzegovina",
    Value: "63",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Bosnia and Herzegovina",
    Value: "63",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Bosnia and Herzegovina",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Bosnia and Herzegovina",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Bosnia and Herzegovina",
    Value: "9",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Bosnia and Herzegovina",
    Value: "2.35",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Brazil",
    Value: "145",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Brazil",
    Value: "51",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Brazil",
    Value: "415",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Brazil",
    Value: "29",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Brazil",
    Value: "84",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Brazil",
    Value: "15",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Brazil",
    Value: "400",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Brazil",
    Value: "194",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Brazil",
    Value: "283",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Brazil",
    Value: "528",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Brazil",
    Value: "528",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Brazil",
    Value: "56",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Brazil",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Brazil",
    Value: "185",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Brazil",
    Value: "1.95",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Canada",
    Value: "4468",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Canada",
    Value: "2838",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Canada",
    Value: "11618",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Canada",
    Value: "2516",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Canada",
    Value: "1971",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Canada",
    Value: "10145",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Canada",
    Value: "1473",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Canada",
    Value: "38",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Canada",
    Value: "13229",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Canada",
    Value: "16105",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Canada",
    Value: "16105",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Canada",
    Value: "2014",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Canada",
    Value: "67",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Canada",
    Value: "67",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Canada",
    Value: "2.96",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Chile",
    Value: "12",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Chile",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Chile",
    Value: "82",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Chile",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Chile",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Chile",
    Value: "5",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Chile",
    Value: "77",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Chile",
    Value: "30",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Chile",
    Value: "52",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Chile",
    Value: "82",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Chile",
    Value: "82",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Chile",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Chile",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Chile",
    Value: "26",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Chile",
    Value: "4.33",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "China",
    Value: "889",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "China",
    Value: "176",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "China",
    Value: "4900",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "China",
    Value: "162",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "China",
    Value: "1",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "China",
    Value: "1600",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "China",
    Value: "3300",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "China",
    Value: "2305",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "China",
    Value: "2582",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "China",
    Value: "5063",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "China",
    Value: "5063",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "China",
    Value: "1",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "China",
    Value: "57",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "China",
    Value: "2305",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "China",
    Value: "2.9",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Colombia",
    Value: "10",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Colombia",
    Value: "10",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Colombia",
    Value: "150",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Colombia",
    Value: "9",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Colombia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Colombia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Colombia",
    Value: "150",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Colombia",
    Value: "129",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Colombia",
    Value: "20",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Colombia",
    Value: "159",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Colombia",
    Value: "159",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Colombia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Colombia",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Colombia",
    Value: "129",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Colombia",
    Value: "2",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Ecuador",
    Value: "45",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Ecuador",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Ecuador",
    Value: "50",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Ecuador",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Ecuador",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Ecuador",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Ecuador",
    Value: "50",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Ecuador",
    Value: "25",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Ecuador",
    Value: "25",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Ecuador",
    Value: "50",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Ecuador",
    Value: "50",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Ecuador",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Ecuador",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Ecuador",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Ecuador",
    Value: "0.56",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Egypt",
    Value: "97",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Egypt",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Egypt",
    Value: "137",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Ending Stocks",
    Country_Name: "Egypt",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Exports",
    Country_Name: "Egypt",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Feed Dom. Consumption",
    Country_Name: "Egypt",
    Value: "77",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "FSI Consumption",
    Country_Name: "Egypt",
    Value: "60",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Imports",
    Country_Name: "Egypt",
    Value: "38",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Production",
    Country_Name: "Egypt",
    Value: "99",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Distribution",
    Country_Name: "Egypt",
    Value: "137",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Total Supply",
    Country_Name: "Egypt",
    Value: "137",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Exports",
    Country_Name: "Egypt",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imp. from U.S.",
    Country_Name: "Egypt",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "TY Imports",
    Country_Name: "Egypt",
    Value: "71",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Yield",
    Country_Name: "Egypt",
    Value: "1.02",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Area Harvested",
    Country_Name: "Eritrea",
    Value: "46",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Beginning Stocks",
    Country_Name: "Eritrea",
    Value: "0",
  },
  {
    Commodity_Description: "Barley",
    Market_Year: "2000",
    Attribute_Description: "Domestic Consumption",
    Country_Name: "Eritrea",
    Value: "31",
  },
];
